### ISSUE TITLE
SDMetric Version and eval_density.py.

### ISSUE THREAD

**Issue by jacobyokehongsi** [amazon-science/tabsyn#11]
Hi @hengruizhang98 ,

Hope you are having a great week!

When trying to run "Density estimation of single column and pair-wise correlation" using "python eval/eval_density.py --dataname [NAME_OF_DATASET] --model [METHOD_NAME] --path [PATH_TO_SYNTHETIC_DATA]", we were wondering which SDMetric Version was used? 

Additionally, out of coverage.csv, quality.txt, shape.csv, and trend.csv, which of these files are used to report "Error rate (%) of column-wise density estimation" and  "Error rate (%) of pair-wise column correlation score" in Tables 1 and 2 of your paper?

Thank you very much!

**Comment by hengruizhang98** [comment]
When conducting experiments, I use the version "'0.11.1'". I am not sure if the codes are compatible with the latest version.

shape is for column-wise while trend is for pair-wise. But shape and trend measures the accuracy while Table 1/2 measures the error, so you have to use 100% to subtract the values in shape/trend to get the results in Table1/2.

**Comment by jacobyokehongsi** [comment]
Hi @hengruizhang98,

Thank you very much for this! I was also wondering if you could share the code of visualisation of Figure 6 (heatmaps of pair-wise column correlations)? It would be greatly appreciated!

Thank you once again!

**Comment by hengruizhang98** [comment]
> Hi @hengruizhang98,
> 
> Thank you very much for this! I was also wondering if you could share the code of visualisation of Figure 6 (heatmaps of pair-wise column correlations)? It would be greatly appreciated!
> 
> Thank you once again!

Below is my codes, you can modify the file path for your data.

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os
import matplotlib.patches as patches
fig = plt.figure(figsize=(44, 21))

size_dict = {
    'adult': 15,
    'default': 24,
    'shoppers': 19,
    'news': 49,
}

name_dict = {
    0: 'CTGAN',
    1: 'TVAE',
    2: 'GReaT',
    3: 'GOGGLE',
    4: 'CoDi',
    6: 'TabDDPM',
    5: 'STaSy',
    7: 'TabSyn',
}

data_dict = {
    0: 'Adult',
    1: 'Default',
    2: 'Shoppers',
    3: 'News',
}



for idx, dataname in enumerate(['adult', 'default', 'shoppers', 'news']):
    path1 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/ctgan_1/trend.csv'
    path2 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/tvae_1/trend.csv'
    path3 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/great_1/trend.csv'
    path4 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/goggle_1/trend.csv'
    path5 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/codi_1/trend.csv'
    path6 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/stasy_1/trend.csv'
    path7 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/tab-ddpm_1/trend.csv'
    path8 = f'/home/hengrui/Codes/tabular-generative-models/eval/density/{dataname}/model_4/trend.csv'

    df1 = pd.read_csv(path1)
    df2 = pd.read_csv(path2)
    
    if os.path.exists(path3):
        df3 = pd.read_csv(path3)
    else:
        df3 = None
    df4 = pd.read_csv(path4)
    df5 = pd.read_csv(path5)
    df6 = pd.read_csv(path6)
    df7 = pd.read_csv(path7)
    df8 = pd.read_csv(path8)

    dfs = [df1, df2, df3, df4, df5, df6, df7, df8]
    corrs = []

    for df in dfs:
        try:
            result = np.zeros((size_dict[dataname],size_dict[dataname]))
            row = df['Column 1'].to_numpy()
            col = df['Column 2'].to_numpy()
            score = df['Score'].to_numpy()

            for i in range(len(row)):
                result[row[i]][col[i]] = 1-score[i]
                result[col[i]][row[i]] = 1-score[i]

            corrs.append(result)
        except:
            corrs.append([1])


    cmap = sns.cubehelix_palette(start=2, rot=0, dark=0.2, light=0.98, reverse=False, gamma=1, as_cmap=True)
    linewidth = 0
    linecolor = 'black'
    annot = False
    vmin = 0
    vmax = 0.8
    
    for i, corr in enumerate(corrs):
      
        ax = fig.add_subplot(4, 8, idx * 8 + i+1)
        if len(corr) != 1:
            sns.heatmap(corr, cmap=cmap, annot=annot, fmt='.2f', linewidths=linewidth, linecolor=linecolor,
                xticklabels=False, yticklabels=False, cbar=False, vmin = vmin, vmax = vmax)
            
        else:
            x = [0.3, 0.7]
            y = [0.3, 0.7]
            line1 = patches.Polygon(list(zip(x, y)), closed=None, fill=False, edgecolor='red', linewidth=2)
            x = [0.3, 0.7]
            y = [0.7, 0.3]
            line2 = patches.Polygon(list(zip(x, y)), closed=None, fill=False, edgecolor='red', linewidth=2)

       
            ax.add_patch(line1)
            ax.add_patch(line2)

            ax.set_xlim(0, 1)
            ax.set_ylim(0, 1)
            ax.set_aspect('equal')
            
            ax.set_xticks([])
            ax.set_yticks([])
            ax.set_xlabel('')
            ax.set_ylabel('')


        if idx == 0:
            ax.text(0.5, 1.08, name_dict[i], transform=ax.transAxes, ha='center', va='center', rotation=0,
                    fontsize=38)
            
        if i == 0:
            ax.text(-0.1, 0.5, data_dict[idx], transform=ax.transAxes, ha='center', va='center', rotation=90,
                    fontsize=40)
            
cbar_ax = fig.add_axes([0.92, 0.15, 0.02, 0.7])
cbar = fig.colorbar(ax.collections[0], cax=cbar_ax)
cbar.ax.tick_params(labelsize=40)


plt.savefig('figs/heat_map.pdf', dpi=300)

plt.show()

**Comment by jacobyokehongsi** [comment]
Hi @hengruizhang98,

Thank you so much for your prompt replies! One last question, the correlation coefficients of categorical columns in trend.csv are missing. In SDMetrics, ContingencySimilarity only outputs the score, but doesn't output the correlation. Thus, how should we calculate the correlation between categorical-categorical columns and categorical-numerical columns?

Thank you once again!

**Comment by hengruizhang98** [comment]
> Hi @hengruizhang98,
> 
> Thank you so much for your prompt replies! One last question, the correlation coefficients of categorical columns in trend.csv are missing. In SDMetrics, ContingencySimilarity only outputs the score, but doesn't output the correlation. Thus, how should we calculate the correlation between categorical-categorical columns and categorical-numerical columns?
> 
> Thank you once again!

According to the official guide of SDMetrics, the correlation between categorical-categorical columns is measured by the Contingency Score, which is computed based on the joint frequency of categorical column pairs. You can find more details in Appendix E.3.2. For categorical-numerical columns, the numerical  columns are first transformed into categorical ones by discretizing the numerical columns into bins, then apply "ContingencySimilarity"  (https://docs.sdv.dev/sdmetrics/reports/quality-report/whats-included). I recommend check the source codes of sdmetrics for details.

**Comment by jacobyokehongsi** [comment]
Thank you so much @hengruizhang98, your help is greatly appreciated!
