### ISSUE TITLE
Reproducing DCR Score

### ISSUE THREAD

**Issue by jacobyhsi** [amazon-science/tabsyn#18]
Hi @hengruizhang98 ,

Hope all is well! I tried reproducing your DCR score results on the default dataset per your paper. 
![image](https://github.com/amazon-science/tabsyn/assets/60124909/9a510272-d1dd-44d4-827d-76227622c577).

The following commands were run:

python main.py --dataname default --method vae --mode train --gpu 0
python main.py --dataname default --method tabsyn --mode train --gpu 0
python main.py --dataname default --method tabsyn --mode sample --gpu 0
python eval/eval_dcr.py --dataname default --model tabsyn --path synthetic/default/tabsyn.csv

However, I am unable to reproduce your results:

![image](https://github.com/amazon-science/tabsyn/assets/60124909/b8d4070e-59d5-488c-9223-94973d90b8c2)

Would you please elaborate on this?

Thank you!

**Comment by jacobyokehongsi** [comment]
Following up on my previous comment, I am unable to reproduce TabDDPM's results either.

![image](https://github.com/amazon-science/tabsyn/assets/60124909/8c4f805d-15a0-46fc-92b1-0832616dbd4a)

**Comment by hengruizhang98** [comment]
Hi, thanks for your question!

To perform DCR experiments, you have to resplit the dataset into a training/holdout (testing) set such that they **have the same size**, then train the generative models based on the training set. The imbalance between the sizes of the training/holdout set will also change the optimal DCR score. Please retry using the new splits.

We apologize for not clarifying it, and we will fix it later.

**Comment by hengruizhang98** [comment]
> Hi, thanks for your question!
> 
> To perform DCR experiments, you have to resplit the dataset into a training/holdout (testing) set such that they **have the same size**, then train the generative models based on the training set. The imbalance between the sizes of the training/holdout set will also change the optimal DCR score. Please retry using the new splits.
> 
> We apologize for not clarifying it, and we will fix it later.

It was stated in page 26, last line, but not in this repository.

**Comment by hengruizhang98** [comment]
@jacobyokehongsi, Hi, have your issue been solved? Don't hesitate to ask additional questions if there is any.

**Comment by jacobyokehongsi** [comment]
Hi @hengruizhang98 , 

Yes!!! Thank you so much for your prompt replies and help! It is greatly appreciated!!!
