### ISSUE TITLE
Reproducing Results in Paper

### ISSUE THREAD

**Issue by QDKStorm** [amazon-science/tabsyn#23]
I'm having some problems trying to reproduce the code for the paper: the data I'm getting doesn't quite match the data in the paper, and I've noticed that #19 mentions the same problem as me, and that the data I'm getting is very similar to the data in that issue, but the bug mentioned in #19 is supposed to be fixed already, so I'm not sure if it's a problem with the code or just me!

Here's a comparison of the data in the paper with the data I got:
  - Density Estimation
![image](https://github.com/user-attachments/assets/19cd0724-0dc9-4492-aaf6-831f296bebe1)
![image](https://github.com/user-attachments/assets/0cc4eefa-2988-494a-a3bf-562909d4717b)
  - Alpha-precision & beta-recall
![image](https://github.com/user-attachments/assets/0e2754f8-ddf8-41d4-ab57-48ca41956a10)
![image](https://github.com/user-attachments/assets/03993cb3-8761-436f-9369-85c4076e8792)

I followed the steps in the README to the letter.

**Comment by hengruizhang98** [comment]
It's very strange. On my end (using the latest code), I just obtain the following results:
<img width="824" alt="image" src="https://github.com/user-attachments/assets/75aa38f1-5a2b-4015-b509-89156a153b7c">

The quality of VAE's embeddings have an huge impact on the performance. Have you trained the VAE thoroughly?

**Comment by QDKStorm** [comment]
Sorry, it was my problem, my python version didn't match the one in the README, which led to some packages not being quite right, which in turn led to this problem. Now it's working fine.
